title: Programming Journal
description: Daily code snippets, development notes, and programming reflections
theme: just-the-docs

url: https://zhixialin.github.io/programming-journal
baseurl: "/programming-journal"
plugins:
  - jekyll-default-layout


# 添加导航栏标签页
nav:
  - title: "Home"
    url: "/"
  - title: "Test"
    url: "/test"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "MIT Licensed | Copyright © Zhixia Lin 2025"