title: Blog
description: Daily code snippets, development notes, and programming reflections
theme: just-the-docs

url: https://zhixialin.github.io
baseurl: "/blog"

destination: ./_site

plugins:
  - jekyll-default-layout

# Markdown 处理器配置
kramdown:
  # 将单个回车渲染为换行
  hard_wrap: true

just_the_docs:
  navigation:
    structure: nested

aux_links:
  Github Repository: https://github.com/ZhixiaLin/blog

footer_content: "MIT Licensed | Copyright © Zhixia Lin 2025"