title: Programming Journal
description: Daily code snippets, development notes, and programming reflections
theme: just-the-docs

url: https://zhixialin.github.io/programming-journal
baseurl: "/programming-journal"
plugins:
  - jekyll-default-layout


just_the_docs:
  navigation:
    structure: nested

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "MIT Licensed | Copyright © Zhixia Lin 2025"